### ISSUE TITLE
License for VCV module?

### ISSUE THREAD

**Issue by michelezaccagnini** [Cycling74/rnbo.example.vcvrack#5]
Since I am planning to release my VCV modules I am wondering what should I write in the license. I was planning to use GNU license. These modules will be free. I have changed the widget completely but the `process` is all coming from my rnbo patch compiled using `rnbo.example.vcvrack`. I know I should credit both Cycling74 and the author of `rnbo.example.vcvrack`, just wondering how since this is my first release outside of Max.

**Comment by jkcmusork** [comment]
Hi Michele,

Great! Simply including the licenses that are in the RNBO source code in your open source distribution should be enough for our needs. If you'd like to make additional mention elsewhere, great, but we don't require it. 

If you have further questions about licensing, please see the [RNBO Licensing FAQ](https://support.cycling74.com/hc/en-us/articles/10730637742483-RNBO-Export-Licensing-FAQ) and reach out to licensing@cycling74.com if necessary, since we're a little less active here.

-Joshua
